def build(bld):
  bld.program(features = 'cxx',
      source       = 'uniqueTest.cpp',
      target       = 'uniqueTest',
      install_path  = None,
      includes     = '. ../src/emitters',
      use = 'szaru')
