def build(bld):
  bld(source = """
  emitters/szlunique.cc
  emitters/top.cc
  emitters/quantile.cc
  public/hashutils.cc
  """,
      features ='cxx cxxshlib',
      name     = 'szaru',
      target   = 'szaru',
      lib = 'ssl',
      includes     = '.')
